//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.17929
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class SQLCreator {

	public const string MON_SELECT = "SELECT k.*, a.vl_strenght, a.vl_agility, a.vl_toughness " +
		"FROM karaimon k, attribute_sheet a " +
		"WHERE k.id_attribute_sheet = a.id";


}

