//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.17929
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class SQLCreator {

	public const string MON_SELECT = "SELECT k.*, a.vl_strenght, a.vl_agility, a.vl_toughness " +
		"FROM karaimon k, attribute_sheet a " +
		"WHERE k.id_attribute_sheet = a.id";

	public const string ATT_SELECT = "SELECT at.*, abm.id_attack, abm.id_mon " +
		"FROM attack_by_mon abm, mon_attack at " +
		"WHERE abm.id_mon = {0} AND abm.id_attack = at.id";

	public const string ELEMENT_SELECT = "SELECT * FROM element";
}

