//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18063
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AttackController
{
	public static float resolveAttack(MonAttack attack, Karaimon attacker, Karaimon defender, bool isDefending) {
		attack.usesLeft--;
		float attackerDamage = attacker.attributes.str;
		float attackDamage = attack.strenght;
		int division = isDefending ? 6 : 3; 
		int finalDamage = (int)(attackerDamage * attackDamage / division);
		defender.reduceLife (finalDamage);
		return finalDamage;
	}
}

